; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

; Function Attrs: convergent norecurse nounwind
define dso_local i32 @sumpi(i32 noundef %a) {
; VENTUS-LABEL: sumpi:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vadd.vi v0, v0, 5
; VENTUS-NEXT:    ret
entry:
  %add = add i32 %a, 5
  ret i32 %add
}

; Function Attrs: convergent norecurse nounwind
define dso_local i32 @sumni(i32 noundef %a) {
; VENTUS-LABEL: sumni:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vsub12.vi v0, v0, 5
; VENTUS-NEXT:    ret
entry:
  %add = add i32 %a, -5
  ret i32 %add
}

