; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

@foo.b = internal addrspace(3) global [5 x i32] undef, align 4

define ventus_kernel void @foo(ptr addrspace(1) noundef align 4 %out) {
; VENTUS-LABEL: foo:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    addi sp, sp, 8
; VENTUS-NEXT:    .cfi_def_cfa_offset 8
; VENTUS-NEXT:    addi tp, tp, 20
; VENTUS-NEXT:    .cfi_def_cfa_offset 20
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    sw ra, -8(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    .cfi_offset ra, 0
; VENTUS-NEXT:    lw t2, 0(a0)
; VENTUS-NEXT:    csrr t0, CSR_LDS
; VENTUS-NEXT:    addi t1, tp, -20
; VENTUS-NEXT:    vmv.v.x v0, t1
; VENTUS-NEXT:    vmv.v.x v1, t0
; VENTUS-NEXT:    sw t2, -4(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    vmv.v.x v2, t2
; VENTUS-NEXT:    call bar
; VENTUS-NEXT:    vmv.v.x v0, zero
; VENTUS-NEXT:    call _Z12get_local_idj
; VENTUS-NEXT:    li t0, 4
; VENTUS-NEXT:    vmv.v.x v1, t0
; VENTUS-NEXT:  .Lpcrel_hi0:
; VENTUS-NEXT:    auipc t1, %pcrel_hi(.LBB0_3)
; VENTUS-NEXT:    setrpc zero, t1, %pcrel_lo(.Lpcrel_hi0)
; VENTUS-NEXT:    vbltu v1, v0, .LBB0_2
; VENTUS-NEXT:    j .LBB0_1
; VENTUS-NEXT:  .LBB0_1: # %if.then
; VENTUS-NEXT:    vsll.vi v0, v0, 2
; VENTUS-NEXT:    addi t0, tp, -20
; VENTUS-NEXT:    # kill: def $v1 killed $x5
; VENTUS-NEXT:    vadd.vx v1, v0, t0
; VENTUS-NEXT:    vlw.v v1, 0(v1)
; VENTUS-NEXT:    csrr t0, CSR_LDS
; VENTUS-NEXT:    vadd.vx v2, v0, t0
; VENTUS-NEXT:    vlw12.v v2, 0(v2)
; VENTUS-NEXT:    lw t1, -4(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    vadd.vx v0, v0, t1
; VENTUS-NEXT:    vlw12.v v3, 0(v0)
; VENTUS-NEXT:    # kill: def $v4 killed $x5
; VENTUS-NEXT:    # kill: def $v4 killed $x6
; VENTUS-NEXT:    vmadd.vv v2, v1, v3
; VENTUS-NEXT:    vsw12.v v2, 0(v0)
; VENTUS-NEXT:    j .LBB0_3
; VENTUS-NEXT:  .LBB0_2: # %if.else
; VENTUS-NEXT:    vmv.v.x v1, zero
; VENTUS-NEXT:    vsll.vi v0, v0, 2
; VENTUS-NEXT:    lw t0, -4(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    # kill: def $v2 killed $x5
; VENTUS-NEXT:    vadd.vx v0, v0, t0
; VENTUS-NEXT:    vsw12.v v1, 0(v0)
; VENTUS-NEXT:  .LBB0_3: # %if.end
; VENTUS-NEXT:    # Label of block must be emitted
; VENTUS-NEXT:    join zero, zero, 0
; VENTUS-NEXT:    lw ra, -8(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    addi sp, sp, -8
; VENTUS-NEXT:    addi tp, tp, -20
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    ret
entry:
  %a = alloca [5 x i32], align 4, addrspace(5)
  call void @llvm.lifetime.start.p5(i64 20, ptr addrspace(5) %a)
  call void @bar(ptr addrspace(5) noundef %a, ptr addrspace(3) noundef @foo.b, ptr addrspace(1) noundef %out)
  %call = call i32 @_Z12get_local_idj(i32 noundef 0)
  %cmp = icmp ult i32 %call, 5
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %arrayidx = getelementptr inbounds [5 x i32], ptr addrspace(5) %a, i32 0, i32 %call
  %0 = load i32, ptr addrspace(5) %arrayidx, align 4
  %arrayidx1 = getelementptr inbounds [5 x i32], ptr addrspace(3) @foo.b, i32 0, i32 %call
  %1 = load i32, ptr addrspace(3) %arrayidx1, align 4
  %mul = mul nsw i32 %1, %0
  %arrayidx2 = getelementptr inbounds i32, ptr addrspace(1) %out, i32 %call
  %2 = load i32, ptr addrspace(1) %arrayidx2, align 4
  %add = add nsw i32 %2, %mul
  store i32 %add, ptr addrspace(1) %arrayidx2, align 4
  br label %if.end

if.else:                                          ; preds = %entry
  %arrayidx3 = getelementptr inbounds i32, ptr addrspace(1) %out, i32 %call
  store i32 0, ptr addrspace(1) %arrayidx3, align 4
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  call void @llvm.lifetime.end.p5(i64 20, ptr addrspace(5) %a)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p5(i64 immarg, ptr addrspace(5) nocapture)

; Function Attrs: convergent
declare dso_local void @bar(ptr addrspace(5) noundef, ptr addrspace(3) noundef, ptr addrspace(1) noundef)

; Function Attrs: convergent mustprogress nofree nounwind willreturn memory(none)
declare dso_local i32 @_Z12get_local_idj(i32 noundef)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p5(i64 immarg, ptr addrspace(5) nocapture)

@global_int = local_unnamed_addr addrspace(1) global i32 12, align 4
@global_short = local_unnamed_addr addrspace(1) global i16 12, align 2
@global_char = local_unnamed_addr addrspace(1) global i8 12, align 1
@cons = local_unnamed_addr addrspace(4) constant i32 5, align 4

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local void @local_memmory(ptr addrspace(3) nocapture noundef %a) local_unnamed_addr{
; VENTUS-LABEL: local_memmory:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vlw12.v v1, 0(v0)
; VENTUS-NEXT:    lui t0, %hi(global_int)
; VENTUS-NEXT:    lw t0, %lo(global_int)(t0)
; VENTUS-NEXT:    vadd.vx v1, v1, t0
; VENTUS-NEXT:    vsw12.v v1, 0(v0)
; VENTUS-NEXT:    ret
entry:
  %0 = load i32, ptr addrspace(3) %a, align 4
  %1 = load i32, ptr addrspace(1) @global_int, align 4
  %add = add nsw i32 %1, %0
  store i32 %add, ptr addrspace(3) %a, align 4
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: readwrite)
define dso_local void @local_memmory_lhimm(ptr addrspace(3) nocapture noundef %a) local_unnamed_addr{
; VENTUS-LABEL: local_memmory_lhimm:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vlh12.v v1, 10(v0)
; VENTUS-NEXT:    vadd.vi v1, v1, 1
; VENTUS-NEXT:    vsh12.v v1, 10(v0)
; VENTUS-NEXT:    ret
entry:
  %add.ptr = getelementptr inbounds i16, ptr addrspace(3) %a, i32 5
  %0 = load i16, ptr addrspace(3) %add.ptr, align 2
  %add = add i16 %0, 1
  store i16 %add, ptr addrspace(3) %add.ptr, align 2
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: readwrite)
define dso_local void @local_memmory_lbimm(ptr addrspace(3) nocapture noundef %a) local_unnamed_addr {
; VENTUS-LABEL: local_memmory_lbimm:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vlb12.v v1, 5(v0)
; VENTUS-NEXT:    vadd.vi v1, v1, 1
; VENTUS-NEXT:    vsb12.v v1, 5(v0)
; VENTUS-NEXT:    ret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(3) %a, i32 5
  %0 = load i8, ptr addrspace(3) %add.ptr, align 1
  %add = add i8 %0, 1
  store i8 %add, ptr addrspace(3) %add.ptr, align 1
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local void @private_memmory(ptr addrspace(5) nocapture noundef %a) local_unnamed_addr {
; VENTUS-LABEL: private_memmory:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vlw.v v1, 0(v0)
; VENTUS-NEXT:    lui t0, %hi(global_int)
; VENTUS-NEXT:    lw t0, %lo(global_int)(t0)
; VENTUS-NEXT:    vadd.vx v1, v1, t0
; VENTUS-NEXT:    vsw.v v1, 0(v0)
; VENTUS-NEXT:    ret
entry:
  %0 = load i32, ptr addrspace(5) %a, align 4
  %1 = load i32, ptr addrspace(1) @global_int, align 4
  %add = add nsw i32 %1, %0
  store i32 %add, ptr addrspace(5) %a, align 4
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local void @private_memmory_with_offset(ptr addrspace(5) nocapture noundef %a) local_unnamed_addr{
; VENTUS-LABEL: private_memmory_with_offset:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vlw.v v1, 4(v0)
; VENTUS-NEXT:    lui t0, %hi(global_int)
; VENTUS-NEXT:    lw t0, %lo(global_int)(t0)
; VENTUS-NEXT:    vadd.vx v1, v1, t0
; VENTUS-NEXT:    vsw.v v1, 4(v0)
; VENTUS-NEXT:    ret
entry:
  %incdec.ptr = getelementptr inbounds i32, ptr addrspace(5) %a, i32 1
  %0 = load i32, ptr addrspace(5) %incdec.ptr, align 4
  %1 = load i32, ptr addrspace(1) @global_int, align 4
  %add = add nsw i32 %1, %0
  store i32 %add, ptr addrspace(5) %incdec.ptr, align 4
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local void @private_memmory_lh(ptr addrspace(5) nocapture noundef %a) local_unnamed_addr {
; VENTUS-LABEL: private_memmory_lh:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    lui t0, %hi(global_short)
; VENTUS-NEXT:    lh t0, %lo(global_short)(t0)
; VENTUS-NEXT:    vlh.v v1, 0(v0)
; VENTUS-NEXT:    vadd.vx v1, v1, t0
; VENTUS-NEXT:    vsh.v v1, 0(v0)
; VENTUS-NEXT:    ret
entry:
  %0 = load i16, ptr addrspace(5) %a, align 2
  %1 = load i16, ptr addrspace(1) @global_short, align 2
  %add = add i16 %1, %0
  store i16 %add, ptr addrspace(5) %a, align 2
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read)
define dso_local zeroext i16 @private_memmory_lhu(ptr addrspace(5) nocapture noundef readonly %a) local_unnamed_addr {
; VENTUS-LABEL: private_memmory_lhu:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vlhu.v v0, 0(v0)
; VENTUS-NEXT:    ret
entry:
  %0 = load i16, ptr addrspace(5) %a, align 2
  ret i16 %0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read)
define dso_local zeroext i8 @private_memmory_lbu(ptr addrspace(5) nocapture noundef readonly %a) local_unnamed_addr {
; VENTUS-LABEL: private_memmory_lbu:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vlbu.v v0, 0(v0)
; VENTUS-NEXT:    ret
entry:
  %0 = load i8, ptr addrspace(5) %a, align 1
  ret i8 %0
}

define dso_local ventus_kernel void @local_memmory1(ptr addrspace(3) nocapture noundef align 4 %b) {
; VENTUS-LABEL: local_memmory1:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    lw t0, 0(a0)
; VENTUS-NEXT:    csrr t1, CSR_LDS
; VENTUS-NEXT:    add t0, t1, t0
; VENTUS-NEXT:    lw t1, 0(t0)
; VENTUS-NEXT:    addi t1, t1, 1
; VENTUS-NEXT:    sw t1, 0(t0)
; VENTUS-NEXT:    ret
entry:
  %0 = load i32, ptr addrspace(3) %b, align 4
  %add = add nsw i32 %0, 1
  store i32 %add, ptr addrspace(3) %b, align 4
  ret void
}

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: read) vscale_range(1,2048)
define dso_local i32 @stack_space(ptr addrspace(3) nocapture noundef readnone %a, ptr addrspace(3) nocapture noundef readonly %b) {
; VENTUS-LABEL: stack_space:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    addi tp, tp, 64
; VENTUS-NEXT:    .cfi_def_cfa_offset 64
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    vmv.v.x v0, zero
; VENTUS-NEXT:    vlw12.v v1, 0(v1)
; VENTUS-NEXT:    li t0, 11
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -20(v32)
; VENTUS-NEXT:    li t0, 10
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -24(v32)
; VENTUS-NEXT:    li t0, 9
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -28(v32)
; VENTUS-NEXT:    li t0, 8
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -32(v32)
; VENTUS-NEXT:    li t0, 7
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -36(v32)
; VENTUS-NEXT:    li t0, 6
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -40(v32)
; VENTUS-NEXT:    li t0, 5
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -44(v32)
; VENTUS-NEXT:    li t0, 4
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -48(v32)
; VENTUS-NEXT:    li t0, 3
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -52(v32)
; VENTUS-NEXT:    li t0, 2
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -56(v32)
; VENTUS-NEXT:    li t0, 1
; VENTUS-NEXT:    vmv.v.x v2, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v2, -60(v32)
; VENTUS-NEXT:    vand.vi v1, v1, 15
; VENTUS-NEXT:    vsll.vi v1, v1, 2
; VENTUS-NEXT:    addi t0, tp, -64
; VENTUS-NEXT:    vadd.vx v1, v1, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw.v v0, -64(v32)
; VENTUS-NEXT:    vlw.v v0, 0(v1)
; VENTUS-NEXT:    addi tp, tp, -64
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    ret
entry:
  %test = alloca [12 x i32], align 4, addrspace(5)
  call void @llvm.lifetime.start.p5(i64 48, ptr addrspace(5) %test)
  store i32 0, ptr addrspace(5) %test, align 4
  %arrayidx.1 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 1
  store i32 1, ptr addrspace(5) %arrayidx.1, align 4
  %arrayidx.2 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 2
  store i32 2, ptr addrspace(5) %arrayidx.2, align 4
  %arrayidx.3 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 3
  store i32 3, ptr addrspace(5) %arrayidx.3, align 4
  %arrayidx.4 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 4
  store i32 4, ptr addrspace(5) %arrayidx.4, align 4
  %arrayidx.5 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 5
  store i32 5, ptr addrspace(5) %arrayidx.5, align 4
  %arrayidx.6 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 6
  store i32 6, ptr addrspace(5) %arrayidx.6, align 4
  %arrayidx.7 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 7
  store i32 7, ptr addrspace(5) %arrayidx.7, align 4
  %arrayidx.8 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 8
  store i32 8, ptr addrspace(5) %arrayidx.8, align 4
  %arrayidx.9 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 9
  store i32 9, ptr addrspace(5) %arrayidx.9, align 4
  %arrayidx.10 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 10
  store i32 10, ptr addrspace(5) %arrayidx.10, align 4
  %arrayidx.11 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 11
  store i32 11, ptr addrspace(5) %arrayidx.11, align 4
  %0 = load i32, ptr addrspace(3) %b, align 4
  %arrayidx1 = getelementptr inbounds [12 x i32], ptr addrspace(5) %test, i32 0, i32 %0
  %1 = load i32, ptr addrspace(5) %arrayidx1, align 4
  call void @llvm.lifetime.end.p5(i64 48, ptr addrspace(5) %test)
  ret i32 %1
}
