; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

define dso_local spir_kernel void @func(ptr addrspace(1) nocapture noundef align 4 %A, ptr addrspace(3) nocapture noundef readonly align 4 %B) {
; VENTUS-LABEL: func:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    addi sp, sp, 16
; VENTUS-NEXT:    .cfi_def_cfa_offset 16
; VENTUS-NEXT:    sw ra, -4(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    sw s0, -8(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    sw s1, -12(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    vsw.v v32, -16(tp) # 4-byte Folded Spill
; VENTUS-NEXT:    .cfi_offset ra, 12
; VENTUS-NEXT:    .cfi_offset s0, 8
; VENTUS-NEXT:    .cfi_offset s1, 4
; VENTUS-NEXT:    .cfi_offset v32.l, 0
; VENTUS-NEXT:    lw s0, 0(a0)
; VENTUS-NEXT:    lw s1, 4(a0)
; VENTUS-NEXT:    vmv.v.x v0, zero
; VENTUS-NEXT:    call _Z13get_global_idj
; VENTUS-NEXT:    vadd.vx v32, v0, zero
; VENTUS-NEXT:    vmv.v.x v0, zero
; VENTUS-NEXT:    call _Z12get_local_idj
; VENTUS-NEXT:    vsll.vi v0, v0, 2
; VENTUS-NEXT:    vadd.vx v0, v0, s1
; VENTUS-NEXT:    vlw12.v v0, 0(v0)
; VENTUS-NEXT:    vsll.vi v1, v32, 2
; VENTUS-NEXT:    vadd.vx v1, v1, s0
; VENTUS-NEXT:    vlw12.v v2, 0(v1)
; VENTUS-NEXT:    vadd.vv v0, v2, v0
; VENTUS-NEXT:    vsw12.v v0, 0(v1)
; VENTUS-NEXT:    lw ra, -4(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    lw s0, -8(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    lw s1, -12(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    vlw.v v32, -16(tp) # 4-byte Folded Reload
; VENTUS-NEXT:    addi sp, sp, -16
; VENTUS-NEXT:    ret
entry:
  %call = tail call i32 @_Z13get_global_idj(i32 noundef 0)
  %call1 = tail call i32 @_Z12get_local_idj(i32 noundef 0)
  %arrayidx = getelementptr inbounds i32, ptr addrspace(3) %B, i32 %call1
  %0 = load i32, ptr addrspace(3) %arrayidx, align 4
  %arrayidx2 = getelementptr inbounds i32, ptr addrspace(1) %A, i32 %call
  %1 = load i32, ptr addrspace(1) %arrayidx2, align 4
  %add = add nsw i32 %1, %0
  store i32 %add, ptr addrspace(1) %arrayidx2, align 4
  ret void
}

declare dso_local i32 @_Z13get_global_idj(i32 noundef)

declare dso_local i32 @_Z12get_local_idj(i32 noundef)
