; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

; Function Attrs: convergent norecurse nounwind
define dso_local void @barrier() local_unnamed_addr {
; VENTUS-LABEL: barrier:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    barrier x0, x0, 3
; VENTUS-NEXT:    barrier x0, x0, 27
; VENTUS-EMPTY:
; VENTUS-NEXT:    ret
entry:
  tail call void @llvm.riscv.ventus.barrier(i32 noundef 3)
  tail call void @llvm.riscv.ventus.barrier.with.scope(i32 noundef 3, i32 noundef 3)
  ret void
}

; Function Attrs: nounwind
declare void @llvm.riscv.ventus.barrier(i32 immarg)

; Function Attrs: nounwind
declare void @llvm.riscv.ventus.barrier.with.scope(i32 immarg, i32 immarg)

