; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

define dso_local ventus_kernel void @bitcast(float noundef %a, ptr addrspace(5) align 4 %b,  ptr addrspace(3) align 4 %c)  {
; VENTUS-LABEL: bitcast:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    lw t0, 8(a0)
; VENTUS-NEXT:    csrr t1, CSR_LDS
; VENTUS-NEXT:    add t0, t1, t0
; VENTUS-NEXT:    lw t1, 0(a0)
; VENTUS-NEXT:    lw t2, 4(a0)
; VENTUS-NEXT:    vmv.v.x v0, t1
; VENTUS-NEXT:    vmv.v.x v1, t2
; VENTUS-NEXT:    vsw.v v0, 0(v1)
; VENTUS-NEXT:    sw t1, 0(t0)
; VENTUS-NEXT:    ret
entry:
  %conv = bitcast float %a to i32
  %conv1 = bitcast float %a to i32
  store i32 %conv, ptr addrspace(5) %b, align 4
  store i32 %conv1, ptr addrspace(3) %c, align 4
  ret void
}
