; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s


define i32 @foo(i32 noundef %cond, i32 noundef %a, i32 noundef %b, i32 noundef %c) {
; VENTUS-LABEL: foo:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vmv.v.x v5, zero
; VENTUS-NEXT:    vrsub.vi v4, v3, 0
; VENTUS-NEXT:  .Lpcrel_hi0:
; VENTUS-NEXT:    auipc t1, %pcrel_hi(.LBB0_2)
; VENTUS-NEXT:    setrpc zero, t1, %pcrel_lo(.Lpcrel_hi0)
; VENTUS-NEXT:    vbeq v0, v5, .LBB0_2
; VENTUS-NEXT:  # %bb.1: # %entry
; VENTUS-NEXT:    vadd.vx v4, v3, zero
; VENTUS-NEXT:  .LBB0_2: # %entry
; VENTUS-NEXT:    # Label of block must be emitted
; VENTUS-NEXT:    join zero, zero, 0
; VENTUS-NEXT:    vmadd.vv v2, v1, v4
; VENTUS-NEXT:    vadd.vx v0, v2, zero
; VENTUS-NEXT:    ret
entry:
  %tobool.not = icmp eq i32 %cond, 0
  %mul = mul nsw i32 %b, %a
  %0 = sub i32 0, %c
  %retval.0.p = select i1 %tobool.not, i32 %0, i32 %c
  %retval.0 = add i32 %retval.0.p, %mul
  ret i32 %retval.0
}
