; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s


define i32 @foo(i32 noundef %cond, i32 noundef %a, i32 noundef %b, i32 noundef %c) {
; VENTUS-LABEL: foo:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vmv.v.x v4, zero
; VENTUS-NEXT:    vbne v0, v4, .LBB0_2
; VENTUS-NEXT:  # %bb.1:
; VENTUS-NEXT:    vrsub.vi v3, v3, 0
; VENTUS-NEXT:  .LBB0_2: # %entry
; VENTUS-NEXT:    vmadd.vv v2, v1, v3
; VENTUS-NEXT:    vadd.vx v0, v2, zero
; VENTUS-NEXT:    ret
entry:
  %tobool.not = icmp eq i32 %cond, 0
  %mul = mul nsw i32 %b, %a
  %0 = sub i32 0, %c
  %retval.0.p = select i1 %tobool.not, i32 %0, i32 %c
  %retval.0 = add i32 %retval.0.p, %mul
  ret i32 %retval.0
}
