; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none) vscale_range(1,2048)
define dso_local <16 x double> @func(<16 x double> noundef %x, <16 x double> noundef %y) local_unnamed_addr {
; VENTUS-LABEL: func:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    addi sp, sp, 4
; VENTUS-NEXT:    .cfi_def_cfa_offset 4
; VENTUS-NEXT:    addi tp, tp, 256
; VENTUS-NEXT:    .cfi_def_cfa_offset 256
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    sw ra, -4(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v33, -12(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v34, -16(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v35, -20(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v36, -24(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v37, -28(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v38, -32(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v39, -36(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v40, -40(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v41, -44(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v42, -48(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v43, -52(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v44, -56(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v45, -60(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v46, -64(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v47, -68(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v48, -72(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v49, -76(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v50, -80(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v51, -84(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v52, -88(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v53, -92(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v54, -96(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v55, -100(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v56, -104(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v57, -108(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v58, -112(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v59, -116(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v60, -120(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v61, -124(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v62, -128(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v63, -132(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v64, -136(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v65, -140(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v66, -144(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v67, -148(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v68, -152(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v69, -156(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v70, -160(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v71, -164(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v72, -168(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v73, -172(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v74, -176(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v75, -180(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v76, -184(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v77, -188(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v78, -192(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v79, -196(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v80, -200(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v81, -204(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v82, -208(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v83, -212(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v84, -216(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v85, -220(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v86, -224(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v87, -228(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v88, -232(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v89, -236(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v90, -240(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v91, -244(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v92, -248(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v93, -252(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v94, -256(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    .cfi_offset ra, 0
; VENTUS-NEXT:    .cfi_offset v33.l, 0
; VENTUS-NEXT:    .cfi_offset v34.l, 0
; VENTUS-NEXT:    .cfi_offset v35.l, 0
; VENTUS-NEXT:    .cfi_offset v36.l, 0
; VENTUS-NEXT:    .cfi_offset v37.l, 0
; VENTUS-NEXT:    .cfi_offset v38.l, 0
; VENTUS-NEXT:    .cfi_offset v39.l, 0
; VENTUS-NEXT:    .cfi_offset v40.l, 0
; VENTUS-NEXT:    .cfi_offset v41.l, 0
; VENTUS-NEXT:    .cfi_offset v42.l, 0
; VENTUS-NEXT:    .cfi_offset v43.l, 0
; VENTUS-NEXT:    .cfi_offset v44.l, 0
; VENTUS-NEXT:    .cfi_offset v45.l, 0
; VENTUS-NEXT:    .cfi_offset v46.l, 0
; VENTUS-NEXT:    .cfi_offset v47.l, 0
; VENTUS-NEXT:    .cfi_offset v48.l, 0
; VENTUS-NEXT:    .cfi_offset v49.l, 0
; VENTUS-NEXT:    .cfi_offset v50.l, 0
; VENTUS-NEXT:    .cfi_offset v51.l, 0
; VENTUS-NEXT:    .cfi_offset v52.l, 0
; VENTUS-NEXT:    .cfi_offset v53.l, 0
; VENTUS-NEXT:    .cfi_offset v54.l, 0
; VENTUS-NEXT:    .cfi_offset v55.l, 0
; VENTUS-NEXT:    .cfi_offset v56.l, 0
; VENTUS-NEXT:    .cfi_offset v57.l, 0
; VENTUS-NEXT:    .cfi_offset v58.l, 0
; VENTUS-NEXT:    .cfi_offset v59.l, 0
; VENTUS-NEXT:    .cfi_offset v60.l, 0
; VENTUS-NEXT:    .cfi_offset v61.l, 0
; VENTUS-NEXT:    .cfi_offset v62.l, 0
; VENTUS-NEXT:    .cfi_offset v63.l, 0
; VENTUS-NEXT:    .cfi_offset v64.l, 0
; VENTUS-NEXT:    .cfi_offset v65.l, 0
; VENTUS-NEXT:    .cfi_offset v66.l, 0
; VENTUS-NEXT:    .cfi_offset v67.l, 0
; VENTUS-NEXT:    .cfi_offset v68.l, 0
; VENTUS-NEXT:    .cfi_offset v69.l, 0
; VENTUS-NEXT:    .cfi_offset v70.l, 0
; VENTUS-NEXT:    .cfi_offset v71.l, 0
; VENTUS-NEXT:    .cfi_offset v72.l, 0
; VENTUS-NEXT:    .cfi_offset v73.l, 0
; VENTUS-NEXT:    .cfi_offset v74.l, 0
; VENTUS-NEXT:    .cfi_offset v75.l, 0
; VENTUS-NEXT:    .cfi_offset v76.l, 0
; VENTUS-NEXT:    .cfi_offset v77.l, 0
; VENTUS-NEXT:    .cfi_offset v78.l, 0
; VENTUS-NEXT:    .cfi_offset v79.l, 0
; VENTUS-NEXT:    .cfi_offset v80.l, 0
; VENTUS-NEXT:    .cfi_offset v81.l, 0
; VENTUS-NEXT:    .cfi_offset v82.l, 0
; VENTUS-NEXT:    .cfi_offset v83.l, 0
; VENTUS-NEXT:    .cfi_offset v84.l, 0
; VENTUS-NEXT:    .cfi_offset v85.l, 0
; VENTUS-NEXT:    .cfi_offset v86.l, 0
; VENTUS-NEXT:    .cfi_offset v87.l, 0
; VENTUS-NEXT:    .cfi_offset v88.l, 0
; VENTUS-NEXT:    .cfi_offset v89.l, 0
; VENTUS-NEXT:    .cfi_offset v90.l, 0
; VENTUS-NEXT:    .cfi_offset v91.l, 0
; VENTUS-NEXT:    .cfi_offset v92.l, 0
; VENTUS-NEXT:    .cfi_offset v93.l, 0
; VENTUS-NEXT:    .cfi_offset v94.l, 0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v33, v31, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v34, v30, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v35, v29, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v36, v28, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v37, v27, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v38, v26, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v39, v25, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v40, v24, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v41, v23, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v42, v22, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v43, v21, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v44, v20, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v45, v19, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v46, v18, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v47, v17, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v48, v16, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v49, v15, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v50, v14, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v51, v13, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v52, v12, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v53, v11, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v54, v10, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v55, v9, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v56, v8, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v57, v7, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v58, v6, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v59, v5, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v60, v4, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v61, v3, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v62, v2, zero
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v63, -264(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v64, -260(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v65, -272(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v66, -268(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v67, -280(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v68, -276(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v69, -288(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v70, -284(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v71, -296(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v72, -292(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v73, -304(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v74, -300(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v75, -312(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v76, -308(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v77, -320(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v78, -316(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v79, -328(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v80, -324(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v81, -336(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v82, -332(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v83, -344(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v84, -340(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v85, -352(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v86, -348(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v87, -360(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v88, -356(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v89, -368(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v90, -364(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v91, -376(v32)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v92, -372(v32)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vlw.v v2, -384(v32)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vlw.v v3, -380(v32)
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 2
; VENTUS-NEXT:    vadd.vx v93, v0, zero
; VENTUS-NEXT:    regext zero, zero, 2
; VENTUS-NEXT:    vadd.vx v94, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v62, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v61, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v91, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v92, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v61, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v62, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v60, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v59, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v89, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v90, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v59, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v60, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v58, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v57, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v87, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v88, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v57, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v58, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v56, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v55, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v85, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v86, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v55, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v56, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v54, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v53, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v83, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v84, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v53, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v54, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v52, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v51, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v81, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v82, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v51, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v52, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v50, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v49, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v79, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v80, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v49, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v50, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v48, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v47, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v77, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v78, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v47, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v48, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v46, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v45, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v75, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v76, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v45, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v46, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v44, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v43, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v73, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v74, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v43, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v44, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v42, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v41, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v71, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v72, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v41, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v42, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v40, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v39, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v69, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v70, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v39, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v40, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v38, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v37, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v67, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v68, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v37, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v38, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v36, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v35, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v2, v65, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v66, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v35, v0, zero
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vadd.vx v36, v1, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v34, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v1, v33, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v2, v63, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v3, v64, zero
; VENTUS-NEXT:    call __adddf3@plt
; VENTUS-NEXT:    vadd.vx v30, v0, zero
; VENTUS-NEXT:    vadd.vx v31, v1, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v0, v93, zero
; VENTUS-NEXT:    regext zero, zero, 128
; VENTUS-NEXT:    vadd.vx v1, v94, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v2, v61, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v3, v62, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v4, v59, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v5, v60, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v6, v57, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v7, v58, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v8, v55, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v9, v56, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v10, v53, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v11, v54, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v12, v51, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v13, v52, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v14, v49, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v15, v50, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v16, v47, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v17, v48, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v18, v45, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v19, v46, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v20, v43, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v21, v44, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v22, v41, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v23, v42, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v24, v39, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v25, v40, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v26, v37, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v27, v38, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v28, v35, zero
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v29, v36, zero
; VENTUS-NEXT:    lw ra, -4(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v33, -12(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v34, -16(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v35, -20(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v36, -24(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v37, -28(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v38, -32(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v39, -36(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v40, -40(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v41, -44(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v42, -48(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v43, -52(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v44, -56(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v45, -60(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v46, -64(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v47, -68(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v48, -72(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v49, -76(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v50, -80(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v51, -84(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v52, -88(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v53, -92(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v54, -96(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v55, -100(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v56, -104(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v57, -108(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v58, -112(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v59, -116(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v60, -120(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v61, -124(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v62, -128(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v63, -132(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v64, -136(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v65, -140(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v66, -144(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v67, -148(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v68, -152(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v69, -156(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v70, -160(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v71, -164(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v72, -168(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v73, -172(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v74, -176(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v75, -180(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v76, -184(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v77, -188(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v78, -192(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v79, -196(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v80, -200(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v81, -204(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v82, -208(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v83, -212(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v84, -216(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v85, -220(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v86, -224(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v87, -228(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v88, -232(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v89, -236(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v90, -240(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v91, -244(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v92, -248(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v93, -252(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v94, -256(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    addi sp, sp, -4
; VENTUS-NEXT:    addi tp, tp, -256
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    ret
entry:
  %add = fadd <16 x double> %x, %y
  ret <16 x double> %add
}

; Function Attrs: convergent mustprogress nofree norecurse nounwind willreturn memory(argmem: readwrite) vscale_range(1,2048)
define dso_local ventus_kernel void @test_fn(ptr addrspace(1) nocapture noundef readonly align 128 %x, ptr addrspace(1) nocapture noundef readonly align 128 %y, ptr addrspace(1) nocapture noundef writeonly align 128 %dst) {
; VENTUS-LABEL: test_fn:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    addi sp, sp, 16
; VENTUS-NEXT:    .cfi_def_cfa_offset 16
; VENTUS-NEXT:    addi tp, tp, 144
; VENTUS-NEXT:    .cfi_def_cfa_offset 144
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    sw ra, -16(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v33, -12(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v34, -16(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v35, -20(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v36, -24(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v37, -28(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v38, -32(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v39, -36(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v40, -40(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v41, -44(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v42, -48(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v43, -52(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v44, -56(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v45, -60(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v46, -64(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v47, -68(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v48, -72(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v49, -76(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v50, -80(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v51, -84(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v52, -88(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v53, -92(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v54, -96(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v55, -100(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v56, -104(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v57, -108(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v58, -112(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v59, -116(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v60, -120(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v61, -124(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v62, -128(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v63, -132(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v64, -136(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v65, -140(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v66, -144(v32) # 4-byte Folded Spill
; VENTUS-NEXT:    .cfi_offset ra, 0
; VENTUS-NEXT:    .cfi_offset v33.l, 0
; VENTUS-NEXT:    .cfi_offset v34.l, 0
; VENTUS-NEXT:    .cfi_offset v35.l, 0
; VENTUS-NEXT:    .cfi_offset v36.l, 0
; VENTUS-NEXT:    .cfi_offset v37.l, 0
; VENTUS-NEXT:    .cfi_offset v38.l, 0
; VENTUS-NEXT:    .cfi_offset v39.l, 0
; VENTUS-NEXT:    .cfi_offset v40.l, 0
; VENTUS-NEXT:    .cfi_offset v41.l, 0
; VENTUS-NEXT:    .cfi_offset v42.l, 0
; VENTUS-NEXT:    .cfi_offset v43.l, 0
; VENTUS-NEXT:    .cfi_offset v44.l, 0
; VENTUS-NEXT:    .cfi_offset v45.l, 0
; VENTUS-NEXT:    .cfi_offset v46.l, 0
; VENTUS-NEXT:    .cfi_offset v47.l, 0
; VENTUS-NEXT:    .cfi_offset v48.l, 0
; VENTUS-NEXT:    .cfi_offset v49.l, 0
; VENTUS-NEXT:    .cfi_offset v50.l, 0
; VENTUS-NEXT:    .cfi_offset v51.l, 0
; VENTUS-NEXT:    .cfi_offset v52.l, 0
; VENTUS-NEXT:    .cfi_offset v53.l, 0
; VENTUS-NEXT:    .cfi_offset v54.l, 0
; VENTUS-NEXT:    .cfi_offset v55.l, 0
; VENTUS-NEXT:    .cfi_offset v56.l, 0
; VENTUS-NEXT:    .cfi_offset v57.l, 0
; VENTUS-NEXT:    .cfi_offset v58.l, 0
; VENTUS-NEXT:    .cfi_offset v59.l, 0
; VENTUS-NEXT:    .cfi_offset v60.l, 0
; VENTUS-NEXT:    .cfi_offset v61.l, 0
; VENTUS-NEXT:    .cfi_offset v62.l, 0
; VENTUS-NEXT:    .cfi_offset v63.l, 0
; VENTUS-NEXT:    .cfi_offset v64.l, 0
; VENTUS-NEXT:    .cfi_offset v65.l, 0
; VENTUS-NEXT:    .cfi_offset v66.l, 0
; VENTUS-NEXT:    lw t0, 8(a0)
; VENTUS-NEXT:    sw t0, -4(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    lw t0, 4(a0)
; VENTUS-NEXT:    sw t0, -8(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    lw t0, 0(a0)
; VENTUS-NEXT:    sw t0, -12(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    vmv.v.x v0, zero
; VENTUS-NEXT:    call _Z13get_global_idj
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vsll.vi v33, v0, 7
; VENTUS-NEXT:    lw t1, -12(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 64
; VENTUS-NEXT:    vadd.vx v0, v33, t1
; VENTUS-NEXT:    vlw12.v v31, 124(v0)
; VENTUS-NEXT:    vlw12.v v30, 120(v0)
; VENTUS-NEXT:    vlw12.v v29, 116(v0)
; VENTUS-NEXT:    vlw12.v v28, 112(v0)
; VENTUS-NEXT:    vlw12.v v27, 108(v0)
; VENTUS-NEXT:    vlw12.v v26, 104(v0)
; VENTUS-NEXT:    vlw12.v v25, 100(v0)
; VENTUS-NEXT:    vlw12.v v24, 96(v0)
; VENTUS-NEXT:    vlw12.v v23, 92(v0)
; VENTUS-NEXT:    vlw12.v v22, 88(v0)
; VENTUS-NEXT:    vlw12.v v21, 84(v0)
; VENTUS-NEXT:    vlw12.v v20, 80(v0)
; VENTUS-NEXT:    vlw12.v v19, 76(v0)
; VENTUS-NEXT:    vlw12.v v18, 72(v0)
; VENTUS-NEXT:    vlw12.v v17, 68(v0)
; VENTUS-NEXT:    vlw12.v v16, 64(v0)
; VENTUS-NEXT:    vlw12.v v15, 60(v0)
; VENTUS-NEXT:    vlw12.v v14, 56(v0)
; VENTUS-NEXT:    vlw12.v v13, 52(v0)
; VENTUS-NEXT:    vlw12.v v12, 48(v0)
; VENTUS-NEXT:    vlw12.v v11, 44(v0)
; VENTUS-NEXT:    vlw12.v v10, 40(v0)
; VENTUS-NEXT:    vlw12.v v9, 36(v0)
; VENTUS-NEXT:    vlw12.v v8, 32(v0)
; VENTUS-NEXT:    vlw12.v v7, 28(v0)
; VENTUS-NEXT:    vlw12.v v6, 24(v0)
; VENTUS-NEXT:    vlw12.v v5, 20(v0)
; VENTUS-NEXT:    vlw12.v v4, 16(v0)
; VENTUS-NEXT:    vlw12.v v3, 12(v0)
; VENTUS-NEXT:    vlw12.v v2, 8(v0)
; VENTUS-NEXT:    vlw12.v v1, 4(v0)
; VENTUS-NEXT:    vlw12.v v0, 0(v0)
; VENTUS-NEXT:    lw t0, -8(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 65
; VENTUS-NEXT:    vadd.vx v34, v33, t0
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v35, 0(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v36, 4(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v37, 8(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v38, 12(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v39, 16(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v40, 20(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v41, 24(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v42, 28(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v43, 32(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v44, 36(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v45, 40(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v46, 44(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v47, 48(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v48, 52(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v49, 56(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v50, 60(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v51, 64(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v52, 68(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v53, 72(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v54, 76(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v55, 80(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v56, 84(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v57, 88(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v58, 92(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v59, 96(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v60, 100(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v61, 104(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v62, 108(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v63, 112(v34)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw12.v v64, 116(v34)
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw12.v v65, 120(v34)
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw12.v v34, 124(v34)
; VENTUS-NEXT:    addi tp, tp, 128
; VENTUS-NEXT:    li t0, 4
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 2
; VENTUS-NEXT:    vmv.v.x v66, t0
; VENTUS-NEXT:    regext zero, zero, 80
; VENTUS-NEXT:    vsw.v v34, 0(v66)
; VENTUS-NEXT:    li t0, 8
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v65, 0(v34)
; VENTUS-NEXT:    li t0, 12
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 136
; VENTUS-NEXT:    vsw.v v64, 0(v34)
; VENTUS-NEXT:    li t0, 16
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v63, 0(v34)
; VENTUS-NEXT:    li t0, 20
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v62, 0(v34)
; VENTUS-NEXT:    li t0, 24
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v61, 0(v34)
; VENTUS-NEXT:    li t0, 28
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v60, 0(v34)
; VENTUS-NEXT:    li t0, 32
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v59, 0(v34)
; VENTUS-NEXT:    li t0, 36
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v58, 0(v34)
; VENTUS-NEXT:    li t0, 40
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v57, 0(v34)
; VENTUS-NEXT:    li t0, 44
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v56, 0(v34)
; VENTUS-NEXT:    li t0, 48
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v55, 0(v34)
; VENTUS-NEXT:    li t0, 52
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v54, 0(v34)
; VENTUS-NEXT:    li t0, 56
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v53, 0(v34)
; VENTUS-NEXT:    li t0, 60
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v52, 0(v34)
; VENTUS-NEXT:    li t0, 64
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v51, 0(v34)
; VENTUS-NEXT:    li t0, 68
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v50, 0(v34)
; VENTUS-NEXT:    li t0, 72
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v49, 0(v34)
; VENTUS-NEXT:    li t0, 76
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v48, 0(v34)
; VENTUS-NEXT:    li t0, 80
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v47, 0(v34)
; VENTUS-NEXT:    li t0, 84
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v46, 0(v34)
; VENTUS-NEXT:    li t0, 88
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v45, 0(v34)
; VENTUS-NEXT:    li t0, 92
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v44, 0(v34)
; VENTUS-NEXT:    li t0, 96
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v43, 0(v34)
; VENTUS-NEXT:    li t0, 100
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v42, 0(v34)
; VENTUS-NEXT:    li t0, 104
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v41, 0(v34)
; VENTUS-NEXT:    li t0, 108
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v40, 0(v34)
; VENTUS-NEXT:    li t0, 112
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v39, 0(v34)
; VENTUS-NEXT:    li t0, 116
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v38, 0(v34)
; VENTUS-NEXT:    li t0, 120
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v37, 0(v34)
; VENTUS-NEXT:    li t0, 124
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v36, 0(v34)
; VENTUS-NEXT:    li t0, 128
; VENTUS-NEXT:    sub t0, tp, t0
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v34, t0
; VENTUS-NEXT:    regext zero, zero, 72
; VENTUS-NEXT:    vsw.v v35, 0(v34)
; VENTUS-NEXT:    call _Z3minDv16_dS_
; VENTUS-NEXT:    addi tp, tp, -128
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    lw t0, -4(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 65
; VENTUS-NEXT:    vadd.vx v33, v33, t0
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v31, 124(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v30, 120(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v29, 116(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v28, 112(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v27, 108(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v26, 104(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v25, 100(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v24, 96(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v23, 92(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v22, 88(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v21, 84(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v20, 80(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v19, 76(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v18, 72(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v17, 68(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v16, 64(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v15, 60(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v14, 56(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v13, 52(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v12, 48(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v11, 44(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v10, 40(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v9, 36(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v8, 32(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v7, 28(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v6, 24(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v5, 20(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v4, 16(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v3, 12(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v2, 8(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v1, 4(v33)
; VENTUS-NEXT:    regext zero, zero, 8
; VENTUS-NEXT:    vsw12.v v0, 0(v33)
; VENTUS-NEXT:    lw ra, -16(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v33, -12(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v34, -16(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v35, -20(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v36, -24(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v37, -28(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v38, -32(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v39, -36(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v40, -40(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v41, -44(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v42, -48(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v43, -52(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v44, -56(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v45, -60(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v46, -64(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v47, -68(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v48, -72(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v49, -76(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v50, -80(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v51, -84(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v52, -88(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v53, -92(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v54, -96(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v55, -100(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v56, -104(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v57, -108(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v58, -112(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v59, -116(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v60, -120(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v61, -124(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v62, -128(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 9
; VENTUS-NEXT:    vlw.v v63, -132(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v64, -136(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v65, -140(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    regext zero, zero, 10
; VENTUS-NEXT:    vlw.v v66, -144(v32) # 4-byte Folded Reload
; VENTUS-NEXT:    addi sp, sp, -16
; VENTUS-NEXT:    addi tp, tp, -144
; VENTUS-NEXT:    regext zero, zero, 1
; VENTUS-NEXT:    vmv.v.x v32, tp
; VENTUS-NEXT:    ret
; VENTUS=NEXT: li	t0, 4
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 2
; VENTUS=NEXT: vmv.v.x	v66, t0
; VENTUS=NEXT: regext	zero, zero, 80
; VENTUS=NEXT: vsw.v	v34, 0(v66)
; VENTUS=NEXT: li	t0, 8
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 136
; VENTUS=NEXT: vsw.v	v65, 0(v34)
; VENTUS=NEXT: li	t0, 12
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 136
; VENTUS=NEXT: vsw.v	v64, 0(v34)
; VENTUS=NEXT: li	t0, 16
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v63, 0(v34)
; VENTUS=NEXT: li	t0, 20
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v62, 0(v34)
; VENTUS=NEXT: li	t0, 24
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v61, 0(v34)
; VENTUS=NEXT: li	t0, 28
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v60, 0(v34)
; VENTUS=NEXT: li	t0, 32
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v59, 0(v34)
; VENTUS=NEXT: li	t0, 36
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v58, 0(v34)
; VENTUS=NEXT: li	t0, 40
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v57, 0(v34)
; VENTUS=NEXT: li	t0, 44
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v56, 0(v34)
; VENTUS=NEXT: li	t0, 48
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v55, 0(v34)
; VENTUS=NEXT: li	t0, 52
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v54, 0(v34)
; VENTUS=NEXT: li	t0, 56
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v53, 0(v34)
; VENTUS=NEXT: li	t0, 60
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v52, 0(v34)
; VENTUS=NEXT: li	t0, 64
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v51, 0(v34)
; VENTUS=NEXT: li	t0, 68
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v50, 0(v34)
; VENTUS=NEXT: li	t0, 72
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v49, 0(v34)
; VENTUS=NEXT: li	t0, 76
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v48, 0(v34)
; VENTUS=NEXT: li	t0, 80
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v47, 0(v34)
; VENTUS=NEXT: li	t0, 84
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v46, 0(v34)
; VENTUS=NEXT: li	t0, 88
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v45, 0(v34)
; VENTUS=NEXT: li	t0, 92
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v44, 0(v34)
; VENTUS=NEXT: li	t0, 96
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v43, 0(v34)
; VENTUS=NEXT: li	t0, 100
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v42, 0(v34)
; VENTUS=NEXT: li	t0, 104
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v41, 0(v34)
; VENTUS=NEXT: li	t0, 108
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v40, 0(v34)
; VENTUS=NEXT: li	t0, 112
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v39, 0(v34)
; VENTUS=NEXT: li	t0, 116
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v38, 0(v34)
; VENTUS=NEXT: li	t0, 120
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v37, 0(v34)
; VENTUS=NEXT: li	t0, 124
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v36, 0(v34)
; VENTUS=NEXT: li	t0, 128
; VENTUS=NEXT: sub	t0, tp, t0
; VENTUS=NEXT: regext	zero, zero, 1
; VENTUS=NEXT: vmv.v.x	v34, t0
; VENTUS=NEXT: regext	zero, zero, 72
; VENTUS=NEXT: vsw.v	v35, 0(v34)
; VENTUS=NEXT: call	_Z3minDv16_dS_
; VENTUS=NEXT: addi	tp, tp, -128
entry:
  %call = call i32 @_Z13get_global_idj(i32 noundef 0)
  %arrayidx = getelementptr inbounds <16 x double>, ptr addrspace(1) %x, i32 %call
  %0 = load <16 x double>, ptr addrspace(1) %arrayidx, align 128
  %arrayidx1 = getelementptr inbounds <16 x double>, ptr addrspace(1) %y, i32 %call
  %1 = load <16 x double>, ptr addrspace(1) %arrayidx1, align 128
  %call2 = call <16 x double> @_Z3minDv16_dS_(<16 x double> noundef %0, <16 x double> noundef %1)
  %arrayidx3 = getelementptr inbounds <16 x double>, ptr addrspace(1) %dst, i32 %call
  store <16 x double> %call2, ptr addrspace(1) %arrayidx3, align 128
  ret void
}

; Function Attrs: convergent mustprogress nofree nounwind willreturn memory(none)
declare dso_local i32 @_Z13get_global_idj(i32 noundef) local_unnamed_addr #2

; Function Attrs: convergent mustprogress nofree nounwind willreturn memory(none)
declare dso_local <16 x double> @_Z3minDv16_dS_(<16 x double> noundef, <16 x double> noundef) local_unnamed_addr #2
