; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs -O1 < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s


define dso_local ventus_kernel void @fadd(float noundef %c, float noundef %d, ptr addrspace(1) nocapture noundef writeonly align 4 %result)  {
; VENTUS-LABEL: fadd:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    flw t0, 4(a0)
; VENTUS-NEXT:    flw t1, 0(a0)
; VENTUS-NEXT:    fadd.s t0, t1, t0
; VENTUS-NEXT:    lw t1, 8(a0)
; VENTUS-NEXT:    fsw t0, 0(t1)
; VENTUS-NEXT:    ret
entry:
  %add1 = fadd float %c, %d
  store float %add1, ptr addrspace(1) %result, align 4
  ret void
}

define dso_local ventus_kernel void @fsub(float noundef %c, float noundef %d, ptr addrspace(1) nocapture noundef writeonly align 4 %result)  {
; VENTUS-LABEL: fsub:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    flw t0, 4(a0)
; VENTUS-NEXT:    flw t1, 0(a0)
; VENTUS-NEXT:    fsub.s t0, t1, t0
; VENTUS-NEXT:    lw t1, 8(a0)
; VENTUS-NEXT:    fsw t0, 0(t1)
; VENTUS-NEXT:    ret
entry:
  %sub = fsub float %c, %d
  store float %sub, ptr addrspace(1) %result, align 4
  ret void
}

define dso_local ventus_kernel void @fmul(float noundef %c, float noundef %d, ptr addrspace(1) nocapture noundef writeonly align 4 %result)  {
; VENTUS-LABEL: fmul:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    flw t0, 4(a0)
; VENTUS-NEXT:    flw t1, 0(a0)
; VENTUS-NEXT:    fmul.s t0, t1, t0
; VENTUS-NEXT:    lw t1, 8(a0)
; VENTUS-NEXT:    fsw t0, 0(t1)
; VENTUS-NEXT:    ret
entry:
  %mul = fmul float %c, %d
  store float %mul, ptr addrspace(1) %result, align 4
  ret void
}

define dso_local ventus_kernel void @fdiv(float noundef %c, float noundef %d, ptr addrspace(1) nocapture noundef writeonly align 4 %result)  {
; VENTUS-LABEL: fdiv:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    flw t0, 4(a0)
; VENTUS-NEXT:    flw t1, 0(a0)
; VENTUS-NEXT:    fdiv.s t0, t1, t0
; VENTUS-NEXT:    lw t1, 8(a0)
; VENTUS-NEXT:    fsw t0, 0(t1)
; VENTUS-NEXT:    ret
entry:
  %div = fdiv float %c, %d
  store float %div, ptr addrspace(1) %result, align 4
  ret void
}

define dso_local ventus_kernel void @fmadd(float noundef %a, float noundef %b, float noundef %c, ptr addrspace(1) nocapture noundef writeonly align 4 %result)  {
; VENTUS-LABEL: fmadd:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    flw t0, 8(a0)
; VENTUS-NEXT:    flw t1, 4(a0)
; VENTUS-NEXT:    flw t2, 0(a0)
; VENTUS-NEXT:    fmadd.s t0, t2, t1, t0
; VENTUS-NEXT:    lw t1, 12(a0)
; VENTUS-NEXT:    fsw t0, 0(t1)
; VENTUS-NEXT:    ret
entry:
  %div = call float @llvm.fma.f32(float  %a, float  %b, float  %c)
  store float %div, ptr addrspace(1) %result, align 4
  ret void
}

declare float @llvm.fma.f32(float  %a, float  %b, float  %c)
