; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

define ventus_kernel void @constraint_r() {
; VENTUS-LABEL: constraint_r:
; VENTUS:       # %bb.0:
; VENTUS-NEXT:    #APP
; VENTUS-NEXT:    li	t0, 1
; VENTUS-NEXT:    #NO_APP
; VENTUS-NEXT:    ret
entry:
  %0 = call i32 asm sideeffect "li $0, 1", "=r,r"(i32 undef)
  ret void
}
