; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

; Function Attrs: convergent norecurse nounwind
define dso_local ventus_kernel void @loadstore(float noundef %a, float noundef %b, float noundef %c, ptr addrspace(1) %ADDR, ptr addrspace(1) %ADDR1, ptr addrspace(1) %ADDR2) {
; VENTUS-LABEL: loadstore:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    lw t0, 20(a0)
; VENTUS-NEXT:    flw t1, 8(a0)
; VENTUS-NEXT:    lw t2, 16(a0)
; VENTUS-NEXT:    lw s0, 12(a0)
; VENTUS-NEXT:    flw s1, 0(a0)
; VENTUS-NEXT:    flw a1, 4(a0)
; VENTUS-NEXT:    fsw s1, 0(s0)
; VENTUS-NEXT:    fsw a1, 0(t2)
; VENTUS-NEXT:    fsw t1, 0(t0)
; VENTUS-NEXT:    ret
entry:
  store float %a, ptr addrspace(1) %ADDR
  store float %b, ptr addrspace(1) %ADDR1
  store float %c, ptr addrspace(1) %ADDR2
  ret void
}
