; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

@shared_tmp = internal addrspace(3) global [4 x i32] undef, align 4

define dso_local void @f1() {
; VENTUS-LABEL: f1:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    lui t0, %ventus_lds_hi(shared_tmp)
; VENTUS-NEXT:    csrr t1, CSR_LDS
; VENTUS-NEXT:    add t0, t1, t0
; VENTUS-NEXT:    li t1, 1
; VENTUS-NEXT:    sw t1, %ventus_lds_lo(shared_tmp)(t0)
; VENTUS-NEXT:    ret
entry:
  store i32 1, ptr addrspace(3) @shared_tmp, align 4
  ret void
}

define dso_local void @f2() {
; VENTUS-LABEL: f2:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    lui t0, %ventus_lds_hi(shared_tmp)
; VENTUS-NEXT:    csrr t1, CSR_LDS
; VENTUS-NEXT:    add t0, t1, t0
; VENTUS-NEXT:    li t1, 2
; VENTUS-NEXT:    sw t1, %ventus_lds_lo(shared_tmp)(t0)
; VENTUS-NEXT:    ret
entry:
  store i32 2, ptr addrspace(3) @shared_tmp, align 4
  ret void
}

; VENTUS: .type	shared_tmp,@object
; VENTUS: .comm	shared_tmp,16,4
