; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s

define i32 @urem(i32 %a, i32 %b) nounwind {
; VENTUS-LABEL: urem:
; VENTUS:       # %bb.0:
; VENTUS-NEXT:    vremu.vv v2, v1, v0
; VENTUS-NEXT:    ret
  %1 = urem i32 %a, %b
  ret i32 %1
}

define i32 @urem_constant_lhs(i32 %a) nounwind {
; VENTUS-LABEL: urem_constant_lhs:
; VENTUS:       # %bb.0:
; VENTUS-NEXT:    li a1, 10
; VENTUS-NEXT:    vremu.vx v2, v1, a1
; VENTUS-NEXT:    ret
  %1 = urem i32 10, %a
  ret i32 %1
}

define i32 @srem(i32 %a, i32 %b) nounwind {
; VENTUS-LABEL: srem:
; VENTUS:       # %bb.0:
; VENTUS-NEXT:    vrem.vv v2, v1, v0
; VENTUS-NEXT:    ret
  %1 = srem i32 %a, %b
  ret i32 %1
}

define i32 @srem_pow2(i32 %a) nounwind {
; VENTUS-LABEL: srem_pow2:
; VENTUS:       # %bb.0:
; VENTUS-NEXT:    vsra.vi v1, v0, 31
; VENTUS-NEXT:    vsrl.vi v1, v1, 29
; VENTUS-NEXT:    vadd.vv v1, v0, v1
; VENTUS-NEXT:    vandi.vi v1, v1, -8
; VENTUS-NEXT:    vsub.vv v0, v0, v1
; VENTUS-NEXT:    ret
  %1 = srem i32 %a, 8
  ret i32 %1
}

define i32 @srem_pow2_2(i32 %a) nounwind {
; VENTUS-LABEL: srem_pow2_2:
; VENTUS:       # %bb.0:
; VENTUS-NEXT:    srai a1, a0, 31
; VENTUS-NEXT:    srli a1, a1, 16
; VENTUS-NEXT:    add a1, a0, a1
; VENTUS-NEXT:    lui a2, 1048560
; VENTUS-NEXT:    and a1, a1, a2
; VENTUS-NEXT:    sub a0, a0, a1
; VENTUS-NEXT:    ret
  %1 = srem i32 %a, 65536
  ret i32 %1
}

define i32 @srem_constant_lhs(i32 %a) nounwind {
; VENTUS-LABEL: srem_constant_lhs:
; VENTUS:       # %bb.0:
; VENTUS-NEXT:    li a1, -10
; VENTUS-NEXT:    rem a0, a1, a0
; VENTUS-NEXT:    ret
  %1 = srem i32 -10, %a
  ret i32 %1
}
