; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs \
; RUN: -asm-verbose < %s | FileCheck -check-prefix=VENTUS %s

define dso_local ventus_kernel void @usage(ptr addrspace(1) nocapture noundef align 4 %b, ptr addrspace(3) nocapture noundef readonly align 4 %a) local_unnamed_addr #0 {
; VENTUS-LABEL: usage:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    addi sp, sp, 4
; VENTUS-NEXT:    sw ra, -4(sp) # 4-byte Folded Spill
; VENTUS-NEXT:    lw t0, 4(a0)
; VENTUS-NEXT:    csrr t1, CSR_LDS
; VENTUS-NEXT:    add t0, t1, t0
; VENTUS-NEXT:    lw t1, 0(a0)
; VENTUS-NEXT:    lw t0, 0(t0)
; VENTUS-NEXT:    lw t2, 0(t1)
; VENTUS-NEXT:    add t0, t2, t0
; VENTUS-NEXT:    sw t0, 0(t1)
; VENTUS-NEXT:    lw ra, -4(sp) # 4-byte Folded Reload
; VENTUS-NEXT:    addi sp, sp, -4
; VENTUS-NEXT:    ret
entry:
  %0 = load i32, ptr addrspace(3) %a, align 4
  %1 = load i32, ptr addrspace(1) %b, align 4
  %add = add nsw i32 %1, %0
  store i32 %add, ptr addrspace(1) %b, align 4
  ret void
}

; VENTUS: .section	.ventus.resource.usage,"w",@progbits
; VENTUS-NEXT: .p2align	3
; VENTUS-NEXT: .word	3
; VENTUS-NEXT: .word	0
; VENTUS-NEXT: .quad	0
; VENTUS-NEXT: .quad	11
; VENTUS-NEXT: .quad	0
; VENTUS-NEXT: .quad	0
; VENTUS-NEXT: .quad	4
; VENTUS-NEXT: .quad	0

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: readwrite) "frame-pointer"="all"}
