; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mcpu=ventus-gpgpu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=VENTUS %s


define <4 x i32> @foo(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; VENTUS-LABEL: foo:
; VENTUS:       # %bb.0: # %entry
; VENTUS-NEXT:    vadd.vv v0, v4, v0
; VENTUS-NEXT:    vadd.vv v1, v5, v1
; VENTUS-NEXT:    vadd.vv v2, v6, v2
; VENTUS-NEXT:    vadd.vv v3, v7, v3
; VENTUS-NEXT:    ret
entry:
  %add = add <4 x i32> %b, %a
  ret <4 x i32> %add
}

