// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -cl-std=CL2.0 -triple riscv32-unknown-unknown -cl-ext=-cl_khr_subgroups -emit-llvm -o - %s \
// RUN: | FileCheck -check-prefix=VENTUS %s

// VENTUS-LABEL: @test_barrier(
// VENTUS-NEXT:  entry:
// VENTUS-NEXT:    tail call void @llvm.riscv.ventus.barrier(i32 3)
// VENTUS-NEXT:    tail call void @llvm.riscv.ventus.barrier(i32 3)
// VENTUS-NEXT:    tail call void @llvm.riscv.ventus.subgroup.barrier(i32 3)
// VENTUS-NEXT:    ret void
//

void test_barrier()
{
  barrier(3);
  work_group_barrier(3);
  sub_group_barrier(3);
}

// VENTUS-LABEL: @test_memory_scope_barrier(
// VENTUS-NEXT:  entry:
// VENTUS-NEXT:    tail call void @llvm.riscv.ventus.barrier.with.scope(i32 3, i32 3)
// VENTUS-NEXT:    tail call void @llvm.riscv.ventus.subgroup.barrier.with.scope(i32 3, i32 3)
// VENTUS-NEXT:    ret void
//
void test_memory_scope_barrier()
{
  work_group_barrier(3,3);
  sub_group_barrier(3,3);
}
