if(NOT CMAKE_CLC_COMPILE_OBJECT)

	set(CMAKE_CLC_COMPILE_OBJECT
	"<CMAKE_CLC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE> -emit-llvm"
	"<CMAKE_CLC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>.o -c <SOURCE>")
	if( CMAKE_BUILD_TYPE STREQUAL "Debug" )
		# This is only for depveloper's option to build debug
		list(APPEND CMAKE_CLC_COMPILE_OBJECT
		"<CMAKE_CLC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>.s -S  <SOURCE>"
		"<CMAKE_CLC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>.ll -S -emit-llvm <SOURCE>"
		"<CMAKE_CLC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>.o -c <SOURCE>"
		"<CMAKE_CLC_COMPILER> <DEFINES> <INCLUDES> <FLAGS>  -o <OBJECT>.h -E <SOURCE>")
	endif()
endif()

if(NOT CMAKE_CLC_CREATE_STATIC_LIBRARY)
  set(CMAKE_CLC_CREATE_STATIC_LIBRARY
  "<CMAKE_CLC_ARCHIVE> -o <TARGET> <OBJECTS>")
endif()

set(CMAKE_INCLUDE_FLAG_CLC "-I")
